ftl-min-version = ""

[global]
  [global.secrets]
    did_web_portable_did = "inline://IntcInVyaVwiOlwiZGlkOndlYjpsb2NhbGhvc3QlM0E4ODkyOmluZ3Jlc3NcIixcInByaXZhdGVLZXlzXCI6W3tcImt0eVwiOlwiT0tQXCIsXCJjcnZcIjpcIkVkMjU1MTlcIixcImRcIjpcImhPZzc0Rk9DOFFvdjdHMktoV21LZFlKY0ozU0dIaFhVOFhKaXRwUncwVTRyNENOTWFtM3luSlFnN183ZTl6OEpyUEFKTEQzZHRVdThVbEgtc1BTU3hRXCIsXCJ4XCI6XCJLLUFqVEdwdDhweVVJT18tM3ZjX0NhendDU3c5M2JWTHZGSlJfckQwa3NVXCJ9XSxcImRvY3VtZW50XCI6e1wiaWRcIjpcImRpZDp3ZWI6bG9jYWxob3N0JTNBODg5MjppbmdyZXNzXCIsXCJ2ZXJpZmljYXRpb25NZXRob2RcIjpbe1wiaWRcIjpcImRpZDp3ZWI6bG9jYWxob3N0JTNBODg5MjppbmdyZXNzIzBcIixcInR5cGVcIjpcIkpzb25XZWJLZXlcIixcImNvbnRyb2xsZXJcIjpcImRpZDp3ZWI6bG9jYWxob3N0JTNBODg5MjppbmdyZXNzXCIsXCJwdWJsaWNLZXlKd2tcIjp7XCJrdHlcIjpcIk9LUFwiLFwiY3J2XCI6XCJFZDI1NTE5XCIsXCJ4XCI6XCJLLUFqVEdwdDhweVVJT18tM3ZjX0NhendDU3c5M2JWTHZGSlJfckQwa3NVXCJ9fV0sXCJzZXJ2aWNlXCI6W3tcImlkXCI6XCIjZGFwLXJlZ2lzdHJ5XCIsXCJ0eXBlXCI6XCJkYXAtcmVnaXN0cnlcIixcInNlcnZpY2VFbmRwb2ludFwiOltcImh0dHA6Ly9sb2NhbGhvc3Q6ODg5Mi9pbmdyZXNzL2RhcC1yZWdpc3RyeVwiXX1dfSxcIm1ldGFkYXRhXCI6bnVsbH0i"

[modules]
  [modules.daps]
    [modules.daps.secrets]
      FTL_DSN_DAPS_DAPS = "inline://InBvc3RncmVzOi8vcG9zdGdyZXM6c2VjcmV0QGxvY2FsaG9zdDo1NDMyMC9kYXBzX2RhcHM_c3NsbW9kZT1kaXNhYmxlIg"
      FTL_TEST_DSN_DAPS_DAPS = "inline://InBvc3RncmVzOi8vcG9zdGdyZXM6c2VjcmV0QGxvY2FsaG9zdDo1NDMyMC9kYXBzX2RhcHNfdGVzdD9zc2xtb2RlPWRpc2FibGUi"

[executables]
  ftl = ""

[commands]
startup = ["just migrate drop"]
