// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"encoding/json"
	"time"
)

type Dap struct {
	Dbid        int64
	ID          string
	Did         string
	Handle      string
	Proof       json.RawMessage
	DateCreated time.Time
}
