// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateDAP(ctx context.Context, arg CreateDAPParams) error
	GetDAP(ctx context.Context, handle string) (Dap, error)
}

var _ Querier = (*Queries)(nil)
